name: Daily UFC Workflow

on:
  # Runs every morning at 11:30 UTC (which is 7:30 AM EST during standard time)
  schedule:
    - cron: "30 11 * * *"
  workflow_dispatch:

jobs:
  run-ufc-scripts:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
      
      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Check Python version
        run: python --version

      - name: Install requirements from requirements.txt
        working-directory: ./
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          cd mma/ufc/preprocessing
          python3 fight_scraper.py new
          python3 fight_scraper.py next
          python3 fighter_scraper.py new
          python3 odds_scraper.py
          python3 odds_scraper_bkup.py
          python3 processing.py generate
          python3 processing.py new
          cd ..
          cd events
          python3 upload_events.py
          cd ..
          cd training
          python3 train_xgb_model.py
      
      - name: Commit CSV changes
        run: |
          git config --global user.email "ifoster41901@gmail.com"
          git config --global user.name "Isaac Foster"
          
          # Stage updated CSV files; adjust the paths as needed
          git add -f mma/ufc/preprocessing/data/*.csv

          # Commit changes (if there are any)
          git commit -m "Update CSV data from GitHub Action" || echo "No CSV changes to commit"
          
          # Push changes back to the branch that triggered the workflow
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}